# Setup
name:         Yagi Software
tagline:      Baaaa
baseurl:      ""
locale:       "en"
permalink: /articles/:title:output_ext

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
